source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"
use_modular_headers!

target 'WLReqKitDemo' do
pod 'Alamofire'
pod 'RxAtomic' ,:modular_headers => true
pod 'RxSwift'
pod 'RxCocoa'
pod 'ObjectMapper'
end

