source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "10.0"
use_modular_headers!

target 'WLReqKitDemo' do
    pod 'Alamofire'
    pod 'RxAtomic' ,:modular_headers => true
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'ObjectMapper'
    pod 'WLToolsKit'
end

